trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: "Hard Mode Build"
  jobs:
  - job: BuildJob
    displayName: "Build using bash only"
    steps:

    - checkout: self

    - script: |
        echo "=== INSTALLING NODE MANUALLY ==="
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v
        npm -v
      displayName: "Manual Node Installation"

    - script: |
        echo "=== RUNNING BUILD ==="
        cd app
        npm install --no-audit --no-fund
        npm run build
      displayName: "Manual Build Steps"

    - script: |
        echo "Compressing artifact manually..."
        cd app
        tar -czvf ../artifact.tar.gz .
      displayName: "Create Artifact (Manual Tarball)"

    - script: |
        echo "Copying artifact to pipeline workspace..."
        mkdir -p $(Build.ArtifactStagingDirectory)
        cp artifact.tar.gz $(Build.ArtifactStagingDirectory)/
        ls -la $(Build.ArtifactStagingDirectory)
      displayName: "Move Artifact"

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
